;;;----------------------------------------------------------------------------------
;;; Generated by protoc-gen-clojure.  DO NOT EDIT
;;;
;;; GRPC com.google.protobuf.GrpcApi Service Implementation
;;;----------------------------------------------------------------------------------
(ns com.google.protobuf.GrpcApi.server
  (:require [com.google.protobuf :refer :all]
            [com.google.protobuf :as com.google.protobuf]))

;-----------------------------------------------------------------------------
; GRPC GrpcApi
;-----------------------------------------------------------------------------
(defprotocol Service
  (Status [this param])
  (SubmitTx [this param]))

(def GrpcApi-service-name "com.xtdb.protos.GrpcApi")

(defn- Status-dispatch
  [ctx request]
  (Status ctx request))
(defn- SubmitTx-dispatch
  [ctx request]
  (SubmitTx ctx request))

(def ^:const rpc-metadata
  [{:pkg "com.xtdb.protos" :service "GrpcApi" :method "Status" :method-fn Status-dispatch :server-streaming false :client-streaming false :input pb->Empty :output new-StatusResponse}
   {:pkg "com.xtdb.protos" :service "GrpcApi" :method "SubmitTx" :method-fn SubmitTx-dispatch :server-streaming false :client-streaming false :input pb->SubmitRequest :output new-SubmitResponse}])
