;;;----------------------------------------------------------------------------------
;;; Generated by protoc-gen-clojure.  DO NOT EDIT
;;;
;;; GRPC com.xtdb.protos.GrpcApi Service Implementation
;;;----------------------------------------------------------------------------------
(ns com.xtdb.protos.GrpcApi.server
  (:require [com.xtdb.protos :refer :all]
            [com.xtdb.protos :as com.xtdb.protos]
            [com.google.protobuf :as com.google.protobuf]))

;-----------------------------------------------------------------------------
; GRPC GrpcApi
;-----------------------------------------------------------------------------
(defprotocol Service
  (Status [this param])
  (SubmitTx [this param])
  (SpeculativeTx [this param])
  (EntityTx [this param]))

(def GrpcApi-service-name "com.xtdb.protos.GrpcApi")

(defn- Status-dispatch
  [ctx request]
  (Status ctx request))
(defn- SubmitTx-dispatch
  [ctx request]
  (SubmitTx ctx request))
(defn- SpeculativeTx-dispatch
  [ctx request]
  (SpeculativeTx ctx request))
(defn- EntityTx-dispatch
  [ctx request]
  (EntityTx ctx request))

(def ^:const rpc-metadata
  [{:pkg "com.xtdb.protos" :service "GrpcApi" :method "Status" :method-fn Status-dispatch :server-streaming false :client-streaming false :input pb->Empty :output new-StatusResponse}
   {:pkg "com.xtdb.protos" :service "GrpcApi" :method "SubmitTx" :method-fn SubmitTx-dispatch :server-streaming false :client-streaming false :input pb->SubmitRequest :output new-SubmitResponse}
   {:pkg "com.xtdb.protos" :service "GrpcApi" :method "SpeculativeTx" :method-fn SpeculativeTx-dispatch :server-streaming false :client-streaming false :input pb->SpeculativeTxRequest :output new-SpeculativeTxResponse}
   {:pkg "com.xtdb.protos" :service "GrpcApi" :method "EntityTx" :method-fn EntityTx-dispatch :server-streaming false :client-streaming false :input pb->EntityTxRequest :output new-EntityTxResponse}])
