;;;----------------------------------------------------------------------------------
;;; Generated by protoc-gen-clojure.  DO NOT EDIT
;;;
;;; GRPC com.xtdb.protos.GrpcApi Service Implementation
;;;----------------------------------------------------------------------------------
(ns com.xtdb.protos.GrpcApi.server
  (:require [com.xtdb.protos :refer :all]
))

;-----------------------------------------------------------------------------
; GRPC GrpcApi
;-----------------------------------------------------------------------------
(defprotocol Service
  (Status [this param]))

(def GrpcApi-service-name "com.xtdb.protos.GrpcApi")

(defn- Status-dispatch
  [ctx request]
  (Status ctx request))

(def ^:const rpc-metadata
  [{:pkg "com.xtdb.protos" :service "GrpcApi" :method "Status" :method-fn Status-dispatch :server-streaming false :client-streaming false :input pb->Empty :output new-StatusResponse}])
